services:
  postgres:
    image: postgres:latest
    container_name: feedup
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: feedup_teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin